nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
redis:
    build: ./redis
    ports:
        - "6379"
